import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY in environment');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

async function seed() {
  // Seed products from hardcoded catalog
  const { data: existingProducts } = await supabase.from('products').select('id');
  const existingIds = new Set((existingProducts || []).map((p: any) => p.id));

  const products = [
    { id: "gid://shopify/Product/1001", handle: "drums-of-liberation-oversized-tee", name: "DRUMS OF LIBERATION // Oversized Tee", description: "Vintage-washed charcoal black tee with a bold chest typography layout.", price: 55, stock: 434, image_url: "/images/products/drums-of-liberation-oversized-tee-1.jpg", category: "Tees" },
    { id: "gid://shopify/Product/1002", handle: "sun-god-sketch-tee", name: "SUN GOD // Sketch Tee", description: "Off-white mid-weight luxury cotton with a rough charcoal sketch design of Luffy laughing.", price: 45, stock: 348, image_url: "/images/products/sun-god-sketch-tee-1.jpg", category: "Tees" },
    { id: "gid://shopify/Product/1003", handle: "haki-crackle-acid-wash-tee", name: "HAKI CRACKLE // Acid-Wash Tee", description: "Purple-and-black cloud-dye pattern tee with a high-density rubber print icon.", price: 50, stock: 359, image_url: "/images/products/haki-crackle-acid-wash-tee-1.jpg", category: "Tees" },
    { id: "gid://shopify/Product/1004", handle: "wanokuni-typography-long-sleeve", name: "WANOKUNI // Typography Long-Sleeve", description: "Heavyweight long-sleeve cotton tee featuring vertical arm sleeve canvas text prints.", price: 65, stock: 267, image_url: "/images/products/wanokuni-typography-long-sleeve-1.jpg", category: "Tees" },
    { id: "gid://shopify/Product/1005", handle: "monkey-d-legacy-box-logo-tee", name: "MONKEY D. // Legacy Box Logo Tee", description: "Minimalist black luxury blank tee with ultra-clean white-and-red box logo stitching.", price: 45, stock: 300, image_url: "/images/products/monkey-d-legacy-box-logo-tee-1.jpg", category: "Tees" },
    { id: "gid://shopify/Product/1006", handle: "awakening-drop-shoulder-tee", name: "AWAKENING // Drop-Shoulder Tee", description: "Slate gray relaxed fit knit jersey with split-hem side vents.", price: 52, stock: 293, image_url: "/images/products/awakening-drop-shoulder-tee-1.jpg", category: "Tees" },
    { id: "gid://shopify/Product/1007", handle: "will-of-d-minimalist-pocket-tee", name: "WILL OF D // Minimalist Pocket Tee", description: "Sandwashed pocket tee featuring a subtle embroidered semi-circle layout on the pocket.", price: 40, stock: 293, image_url: "/images/products/will-of-d-minimalist-pocket-tee-1.jpg", category: "Tees" },
    { id: "gid://shopify/Product/1008", handle: "emperors-might-graphic-tee", name: "EMPEROR'S MIGHT // Graphic Tee", description: "Deep indigo heavy wash jersey with a geometric Conqueror's aura print.", price: 48, stock: 451, image_url: "/images/products/emperors-might-graphic-tee-1.jpg", category: "Tees" },
    { id: "gid://shopify/Product/1009", handle: "liberator-heavy-knit-tee", name: "LIBERATOR // Heavy-Knit Tee", description: "Pure chalk white featuring a premium tonal raised puff print on the shoulder blades.", price: 58, stock: 566, image_url: "/images/products/liberator-heavy-knit-tee-1.jpg", category: "Tees" },
    { id: "gid://shopify/Product/1010", handle: "pirate-king-split-panel-tee", name: "PIRATE KING // Split Panel Tee", description: "Half-black, half-white structural panels stitched down the center.", price: 55, stock: 419, image_url: "/images/products/pirate-king-split-panel-tee-1.jpg", category: "Tees" },
    { id: "gid://shopify/Product/2001", handle: "nika-liberator-heavyweight-hoodie", name: "NIKA // The Liberator Heavyweight Hoodie", description: "450GSM French Terry cotton in bone white with purple Haki lightning embroidery.", price: 120, stock: 373, image_url: "/images/products/nika-liberator-heavyweight-hoodie-1.jpg", category: "Hoodies & Outerwear" },
    { id: "gid://shopify/Product/2002", handle: "gear-fifth-coach-windbreaker", name: "GEAR FIFTH // Coach Windbreaker", description: "Water-resistant matte white ripstop nylon featuring a hidden reflective Nika cloud pattern.", price: 95, stock: 457, image_url: "/images/products/gear-fifth-coach-windbreaker-1.jpg", category: "Hoodies & Outerwear" },
    { id: "gid://shopify/Product/2003", handle: "onigashima-distressed-denim-jacket", name: "ONIGASHIMA // Distressed Denim Jacket", description: "Acid-washed black denim with a massive back-panel woven tapestry patch.", price: 150, stock: 530, image_url: "/images/products/onigashima-distressed-denim-jacket-1.jpg", category: "Hoodies & Outerwear" },
    { id: "gid://shopify/Product/2004", handle: "supreme-haki-bomber-jacket", name: "SUPREME HAKI // Bomber Jacket", description: "Satin-lined flight jacket featuring purple-and-black structural crackle stitching.", price: 165, stock: 287, image_url: "/images/products/supreme-haki-bomber-jacket-1.jpg", category: "Hoodies & Outerwear" },
    { id: "gid://shopify/Product/2005", handle: "conqueror-velvet-puffer", name: "CONQUEROR // Velvet Puffer", description: "Deep plum velvet oversized crop puffer jacket with thermal heat-retention lining.", price: 180, stock: 444, image_url: "/images/products/conqueror-velvet-puffer-1.jpg", category: "Hoodies & Outerwear" },
    { id: "gid://shopify/Product/2006", handle: "joyboy-knit-cardigan", name: "JOYBOY // Knit Cardigan", description: "Heavy mohair knit cardigan with cloud-white panel patterns and minimalist resin buttons.", price: 110, stock: 422, image_url: "/images/products/joyboy-knit-cardigan-1.jpg", category: "Hoodies & Outerwear" },
    { id: "gid://shopify/Product/2007", handle: "red-force-varsity-jacket", name: "RED FORCE // Varsity Jacket", description: "Wool body with premium white leather sleeves and custom Chenille \"Haki Drop\" chest lettering.", price: 195, stock: 296, image_url: "/images/products/red-force-varsity-jacket-1.jpg", category: "Hoodies & Outerwear" },
    { id: "gid://shopify/Product/2008", handle: "roger-inherited-will-anorak", name: "ROGER // Inherited Will Anorak", description: "Crimson technical windbreaker with a golden embroidery print of the legendary Loguetown coordinates.", price: 130, stock: 362, image_url: "/images/products/roger-inherited-will-anorak-1.jpg", category: "Hoodies & Outerwear" },
    { id: "gid://shopify/Product/2009", handle: "raised-in-wano-kimono-cloak", name: "RAISED IN WANO // Kimono Cloak", description: "Modern streetwear tech-wear haori with a stylized, flowing purple wind trail design.", price: 85, stock: 336, image_url: "/images/products/raised-in-wano-kimono-cloak-1.jpg", category: "Hoodies & Outerwear" },
    { id: "gid://shopify/Product/2010", handle: "emperor-tech-fleece-zip", name: "EMPEROR // Tech-Fleece Zip", description: "Double-knit lightweight performance zip-up hoodie featuring blacked-out heat-sealed tactical zippers.", price: 115, stock: 503, image_url: "/images/products/emperor-tech-fleece-zip-1.jpg", category: "Hoodies & Outerwear" },
    { id: "gid://shopify/Product/3001", handle: "gear-5-reveal-holographic-sticker", name: "GEAR 5 REVEAL // Holographic Sticker", description: "Laser-cut holographic sticker reflecting shifting purples and chromes.", price: 8, stock: 16, image_url: "/images/products/3001-gear5.jpg", category: "Stickers & Decals" },
    { id: "gid://shopify/Product/3002", handle: "haki-crackle-die-cut-vinyl-decal", name: "HAKI CRACKLE // Die-Cut Vinyl Decal", description: "Weatherproof pitch-black and deep purple lightning vinyl decal designed for vehicles or laptops.", price: 6, stock: 37, image_url: "/images/products/3002-haki-crackle.jpg", category: "Stickers & Decals" },
    { id: "gid://shopify/Product/3003", handle: "drums-of-liberation-slap-sticker", name: "DRUMS OF LIBERATION // Slap Sticker", description: "Traditional Japanese city street-style vinyl slap sticker containing high-gloss kanji.", price: 7, stock: 107, image_url: "/images/products/custom-drums.jpg", category: "Stickers & Decals" },
    { id: "gid://shopify/Product/3004", handle: "wano-arc-collectors-sticker-pack", name: "WANO ARC // Collector's Sticker Pack", description: "A premium 10-piece matte-finish sticker set featuring character crest silhouettes.", price: 25, stock: 109, image_url: "/images/products/custom-skulls.png", category: "Stickers & Decals" },
    { id: "gid://shopify/Product/3005", handle: "nika-cloud-mini-sticker-sheet", name: "NIKA CLOUD // Mini Sticker Sheet", description: "A sheet of 15 translucent, textured sticker elements shaped like Nika's floating smoke scarves.", price: 12, stock: 82, image_url: "/images/products/nika-cloud-mini-sticker-sheet-1.jpg", category: "Stickers & Decals" },
    { id: "gid://shopify/Product/3006", handle: "wanokuni-bumper-sticker", name: "WANOKUNI // Bumper Sticker", description: "Long format high-visibility warning style text decal in bold red and white.", price: 9, stock: 106, image_url: "/images/products/3006-wanokuni.jpg", category: "Stickers & Decals" },
    { id: "gid://shopify/Product/3007", handle: "will-of-d-minimalist-emblem-decal", name: "WILL OF D // Minimalist Emblem Decal", description: "Subtle, semi-reflective silver metallic skin sticker.", price: 5, stock: 60, image_url: "/images/products/custom-will-of-d.png", category: "Stickers & Decals" },
    { id: "gid://shopify/Product/3008", handle: "conquerors-lightning-glow-decal", name: "CONQUEROR'S LIGHTNING // Glow Decal", description: "Photoluminescent sticker that charges under light to glow vibrant neon purple in total darkness.", price: 10, stock: 121, image_url: "/images/products/conquerors-lightning-glow-decal-1.jpg", category: "Stickers & Decals" },
    { id: "gid://shopify/Product/3009", handle: "joyboy-retro-chibi-decal", name: "JOYBOY // Retro Chibi Decal", description: "Comic caricature style cut-out layer utilizing premium UV-resistant ink coatings.", price: 6, stock: 57, image_url: "/images/products/custom-joyboy.jpg", category: "Stickers & Decals" },
    { id: "gid://shopify/Product/3010", handle: "haki-drop-holographic-box-logo-pack", name: "HAKI DROP // Holographic Box Logo Pack", description: "A 5-piece luxury bundle of changing iridescent brand logo configurations.", price: 15, stock: 146, image_url: "/images/products/custom-h-holo.png", category: "Stickers & Decals" },
    { id: "gid://shopify/Product/4001", handle: "nika-the-sun-god-gold-foil-art-print", name: "NIKA THE SUN GOD // Gold Foil Art Print", description: "A premium 12x18 heavy cardstock print accented with real metallic gold leafing layers.", price: 45, stock: 3, image_url: "/images/products/custom-4001.jpg", category: "Trading Cards" },
    { id: "gid://shopify/Product/4002", handle: "emperor-luffy-chrome-foil-trading-card", name: "EMPEROR LUFFY // Chrome-Foil Trading Card", description: "Limited-edition custom collector's metal card displaying deep etched serial numbers.", price: 20, stock: 2, image_url: "/images/products/custom-4002.png", category: "Trading Cards" },
    { id: "gid://shopify/Product/4003", handle: "wano-arc-climax-lenticular-3d-print", name: "WANO ARC CLIMAX // Lenticular 3D Print", description: "A poster print shifting dynamically between Base Form Luffy and Gear 5 layout fields upon viewing angle.", price: 55, stock: 25, image_url: "/images/products/custom-4003.jpg", category: "Trading Cards" },
    { id: "gid://shopify/Product/4004", handle: "the-four-emperors-matte-art-poster", name: "THE FOUR EMPERORS // Matte Art Poster", description: "Minimalist black-and-white print tracking the silhouette typography of the Yonko.", price: 35, stock: 103, image_url: "/images/products/custom-4004.jpg", category: "Trading Cards" },
    { id: "gid://shopify/Product/4005", handle: "drums-of-liberation-sound-wave-print", name: "DRUMS OF LIBERATION // Sound-Wave Print", description: "High-gloss graphic visualization map of the drums heartbeat vector typography.", price: 40, stock: 43, image_url: "/images/products/custom-4005.png", category: "Trading Cards" },
    { id: "gid://shopify/Product/4006", handle: "pirate-king-canvas-wall-scroll", name: "PIRATE KING // Canvas Wall Scroll", description: "Traditional woven canvas fabric scroll hanging from modular solid dark walnut wood bars.", price: 65, stock: 40, image_url: "/images/products/custom-4006.png", category: "Trading Cards" },
    { id: "gid://shopify/Product/4007", handle: "conquerors-impact-holo-illustration", name: "CONQUEROR'S IMPACT // Holo Illustration", description: "Iridescent card layout illustrating the initial clash breaking open sky structures.", price: 30, stock: 35, image_url: "/images/products/custom-4007.png", category: "Trading Cards" },
    { id: "gid://shopify/Product/4008", handle: "wanokuni-sketch-variant-print", name: "WANOKUNI // Sketch Variant Print", description: "Lithograph reproduction of rough development sketch panels from the Onigashima invasion mapping.", price: 25, stock: 6, image_url: "/images/products/custom-4008.png", category: "Trading Cards" },
    { id: "gid://shopify/Product/4009", handle: "will-of-d-secret-rare-card-fragment", name: "WILL OF D // Secret Rare Card Fragment", description: "Textured premium collectible stock card framed inside a screw-down acrylic display block.", price: 15, stock: 38, image_url: "/images/products/custom-4009.png", category: "Trading Cards" },
    { id: "gid://shopify/Product/4010", handle: "inherited-will-triple-panel-display", name: "INHERITED WILL // Triple-Panel Display", description: "Triptych format set of three matching minimalist timeline art boards.", price: 90, stock: 72, image_url: "/images/products/custom-4010.png", category: "Trading Cards" },
    { id: "gid://shopify/Product/5001", handle: "gear-5-vinyl-designer-toy", name: "GEAR 5 // Vinyl Designer Toy", description: "An 8-inch high-end soft vinyl art toy depicting Luffy bouncing with a clear smoky support stand base.", price: 110, stock: 95, image_url: "/images/products/custom-5001.jpg", category: "Toys & Figures" },
    { id: "gid://shopify/Product/5002", handle: "nika-nendoroid-scale-action-figure", name: "NIKA // Nendoroid-Scale Action Figure", description: "Fully articulated modular action figure equipped with interchangeable dynamic faces and Haki lightning props.", price: 75, stock: 109, image_url: "/images/products/custom-5002.jpg", category: "Toys & Figures" },
    { id: "gid://shopify/Product/5003", handle: "the-drums-electronic-desktop-drum-replica", name: "THE DRUMS // Electronic Desktop Drum Replica", description: "A micro-prop that thumps out physical, bass-heavy vibrations and LED lighting flashes on button click.", price: 95, stock: 9, image_url: "/images/products/custom-5003.jpg", category: "Toys & Figures" },
    { id: "gid://shopify/Product/5004", handle: "onigashima-brick-building-architecture-set", name: "ONIGASHIMA // Brick Building Architecture Set", description: "An 1,200 piece advanced micro-brick kit to assemble the skull dome structure.", price: 145, stock: 131, image_url: "/images/products/custom-5004.jpg", category: "Toys & Figures" },
    { id: "gid://shopify/Product/5005", handle: "conqueror-custom-resinated-chess-set", name: "CONQUEROR // Custom Resinated Chess Set", description: "High-end chess setup split between deep translucent purple and opaque bone-white custom figures.", price: 250, stock: 22, image_url: "/images/products/custom-5005.jpg", category: "Toys & Figures" },
    { id: "gid://shopify/Product/5006", handle: "luffy-gear-5-plush-plush-collectible", name: "LUFFY GEAR 5 // Plush Plush Collectible", description: "Oversized luxury plush doll sewn with super soft high-pile fleece hair layers.", price: 35, stock: 47, image_url: "/images/products/custom-5006.jpg", category: "Toys & Figures" },
    { id: "gid://shopify/Product/5007", handle: "wano-rooftop-die-cast-vehicle-match", name: "WANO ROOFTOP // Die-Cast Vehicle Match", description: "Scale down custom-painted matte black alloy container truck layout showcasing brand graphics.", price: 25, stock: 119, image_url: "/images/products/custom-5007.jpg", category: "Toys & Figures" },
    { id: "gid://shopify/Product/5008", handle: "haki-compass-mechanical-gyro-spinner", name: "HAKI COMPASS // Mechanical Gyro Spinner", description: "Full-metal structural hand toy utilizing premium ceramic bearing rings for high spin durations.", price: 40, stock: 66, image_url: "/images/products/custom-5008.jpg", category: "Toys & Figures" },
    { id: "gid://shopify/Product/5009", handle: "sun-god-glowing-desktop-orb-lamp", name: "SUN GOD // Glowing Desktop Orb Lamp", description: "3D laser-etched crystal sphere lamp casting custom lighting auras upwards.", price: 85, stock: 17, image_url: "/images/products/custom-5009.jpg", category: "Toys & Figures" },
    { id: "gid://shopify/Product/5010", handle: "monkey-d-poseable-figma-masterpiece", name: "MONKEY D. // Poseable Figma Masterpiece", description: "Collector's grade scale presentation figure detailed with wire-hemmed fabric clothing options.", price: 130, stock: 21, image_url: "/images/products/custom-5010.jpg", category: "Toys & Figures" },
  ];

  for (const p of products) {
    if (!existingIds.has(p.id)) {
      const { error } = await supabase.from('products').insert({
        ...p, created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
      });
      if (error) console.error(`Failed: ${p.name}: ${error.message}`);
      else console.log(`Inserted: ${p.name}`);
    }
  }
  console.log('Seed complete!');
}

seed().catch(console.error);
